openapi: 3.0.3
info:
  title: CEC USER API Documentation
  version: 1.0.12
tags:
- name: 1-3. 대여 신청 / 장비
paths:
  /api/equipments/cart:
    get:
      tags:
      - 1-3. 대여 신청 / 장비
      summary: 장비 장바구니 조회
      operationId: getCartItems
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseListEquipmentResponse'
    post:
      tags:
      - 1-3. 대여 신청 / 장비
      summary: 장비 장바구니 추가
      operationId: addToCart
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
                format: int64
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseVoid'
  /api/equipments/action:
    patch:
      tags:
      - 1-3. 대여 신청 / 장비
      summary: 장비 상태 변경 요청 (대여/반납 요청 및 취소)
      description: 날짜는 대여 요청 시에만 필요
      operationId: handleEquipmentAction
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EquipmentActionRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseVoid'
  /api/equipments:
    get:
      tags:
      - 1-3. 대여 신청 / 장비
      summary: 장비 목록 조회
      operationId: getEquipments
      parameters:
      - name: categoryId
        in: query
        description: 카테고리 ID로 정렬
        required: false
        schema:
          type: string
          description: 카테고리 ID로 정렬
          example: 1
        example: 1
      - name: searchKeyword
        in: query
        description: 검색 키워드 (모델명, 대여자명, 일련번호, 카테고리명)
        required: false
        schema:
          type: string
          description: 검색 키워드 (모델명, 대여자명, 일련번호, 카테고리명)
          example: SONY
        example: SONY
      - name: searchType
        in: query
        description: 검색 타입 (ALL, MODEL_NAME, CATEGORY_NAME, SERIAL_NUMBER, RENTER_NAME)
        required: false
        schema:
          type: string
          enum:
          - ALL
          - MODEL_NAME
          - CATEGORY_NAME
          - RENTER_NAME
        example: ALL
      - name: status
        in: query
        description: 장비 상태 (ALL, AVAILABLE, IN_USE, BROKEN, RENTAL_PENDING, RETURN_PENDING
          중 선택)
        required: false
        schema:
          type: string
          enum:
          - ALL
          - AVAILABLE
          - IN_USE
          - BROKEN
          - RENTAL_PENDING
          - RETURN_PENDING
        example: AVAILABLE
      - name: sortBy
        in: query
        description: 정렬할 필드 (id, createdAt, name 등)
        required: false
        schema:
          type: string
          enum:
          - NAME
          - ID
        example: id
      - name: page
        in: query
        description: 페이지 번호 (기본값 0)
        required: false
        schema:
          type: integer
          description: 페이지 번호 (기본값 0)
          example: 0
        example: 0
      - name: size
        in: query
        description: 페이지당 크기 (기본값 = 10)
        required: false
        schema:
          type: integer
          description: 페이지당 크기 (기본값 = 10)
          example: 10
        example: 10
      - name: sortDirection
        in: query
        description: 정렬 방법
        required: false
        schema:
          type: string
          enum:
          - ASC
          - DESC
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseEquipmentListResponse'
  /api/equipments/{id}:
    get:
      tags:
      - 1-3. 대여 신청 / 장비
      summary: 장비 단일 조회
      operationId: getEquipment
      parameters:
      - name: id
        in: path
        description: 장비 ID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseEquipmentResponse'
components:
  schemas:
    ApiResponseVoid:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        data:
          type: object
    EquipmentActionRequest:
      type: object
      properties:
        action:
          type: string
          description: 'RENT_REQUEST: 대여 요청

            RENT_CANCEL: 대여 요청 취소

            RETURN_REQUEST: 반납 요청

            RETURN_CANCEL: 반납 요청 취소'
          enum:
          - RENT_REQUEST
          - RENT_CANCEL
          - RETURN_REQUEST
          - RETURN_CANCEL
        ids:
          type: array
          description: 장비 ID 목록
          example:
          - 1
          - 2
          - 3
          items:
            type: integer
            description: 장비 ID 목록
            format: int64
        startAt:
          type: string
          description: 요청 시작일 (대여 요청 시에만 필요)
          format: date-time
          nullable: true
        endAt:
          type: string
          description: 요청 종료일 (대여 요청 시에만 필요)
          format: date-time
          nullable: true
    ApiResponseEquipmentListResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        data:
          $ref: '#/components/schemas/EquipmentListResponse'
    EquipmentListResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/EquipmentResponse'
        pageable:
          $ref: '#/components/schemas/PageableInfo'
    EquipmentResponse:
      type: object
      properties:
        modelName:
          type: string
          description: 장비 모델 이름
          example: SONY
        startRentAt:
          type: string
          description: 대여 시작 시간
          nullable: true
          format: date-time
        endRentAt:
          type: string
          description: 대여 종료 시간
          nullable: true
          format: date-time
        renterName:
          type: string
          description: 대여자 이름 또는 사용하는 수업 이름 (대여하지 않은 경우 null)
          nullable: true
          example: 홍길동
        status:
          type: string
          example: AVAILABLE, IN_USE, BROKEN, RENTAL_PENDING 중 하나
          enum:
          - AVAILABLE(대여 가능)
          - IN_USE(대여중)
          - BROKEN(파손)
          - RENTAL_PENDING(대여 신청 중)
          - RETURN_PENDING(반납 처리중)
        createdAt:
          type: string
          description: 장비 등록일
          format: date-time
        imageUrl:
          type: string
          description: 장비 이미지 URL
          example: https://example.com/images/equipment.jpg
    PageableInfo:
      type: object
      properties:
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        totalPages:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
    ApiResponseEquipmentResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        data:
          $ref: '#/components/schemas/EquipmentResponse'
    ApiResponseListEquipmentResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/EquipmentResponse'
