openapi: 3.0.3
info:
  title: CEC USER API Documentation
  version: 1.0.12
tags:
- name: 3-2. 유저 프로필 / 1:1 문의하기
paths:
  /api/inquiry/{id}:
    get:
      tags:
      - 3-2. 유저 프로필 / 1:1 문의하기
      summary: 문의글 상세 조회
      description: 본인이 작성한 문의글 + 답변 내용
      operationId: getInquiry
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseInquiryResponse'
    put:
      tags:
      - 3-2. 유저 프로필 / 1:1 문의하기
      summary: 문의글 수정
      description: 본인이 작성한 문의글을 수정합니다.
      operationId: updateInquiry
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InquiryRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseLong'
    delete:
      tags:
      - 3-2. 유저 프로필 / 1:1 문의하기
      summary: 문의글 삭제
      description: 본인이 작성한 문의글을 삭제합니다.
      operationId: deleteInquiry
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseVoid'
  /api/inquiry:
    get:
      tags:
      - 3-2. 유저 프로필 / 1:1 문의하기
      summary: 내 문의글 목록 조회
      description: 로그인한 사용자의 모든 문의글을 페이지네이션과 함께 조회합니다.
      operationId: getMyInquiries
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 1
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 10
      - name: sortBy
        in: query
        required: false
        schema:
          type: string
          default: createdAt
      - name: sortDirection
        in: query
        required: false
        schema:
          type: string
          default: DESC
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseInquiryListResponse'
    post:
      tags:
      - 3-2. 유저 프로필 / 1:1 문의하기
      summary: 문의글 작성
      description: 인증된 사용자가 제목, 내용, 유형 등을 입력하여 문의글을 작성합니다.
      operationId: createInquiry
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InquiryRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseLong'
components:
  schemas:
    AuthorResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nickname:
          type: string
        role:
          type: string
          enum:
          - ROLE_USER
          - ROLE_ADMIN
          - ROLE_SUPER_ADMIN
        imageUrl:
          type: string
    InquiryRequest:
      required:
      - content
      - title
      - type
      type: object
      properties:
        title:
          type: string
          description: 문의 제목
          example: 장비 대여 관련 문의
        content:
          type: string
          description: 문의 내용
          example: 장비 대여 예약이 되지 않습니다.
        attachments:
          type: array
          items:
            type: string
            description: 첨부파일 URL
            example: https://example.com/image.png, https://example.com/docs.md
        type:
          type: string
          description: 문의 유형
          example: RENTAL
          enum:
          - RENTAL
          - RETURN
          - SYSTEM_ERROR
          - EQUIPMENT_BROKEN
          - PENALTY
          - ETC
    ApiResponseVoid:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        data:
          type: object
    ApiResponseLong:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        data:
          type: integer
          format: int64
    PageableInfo:
      type: object
      properties:
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        totalPages:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
    ApiResponseInquiryResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        data:
          $ref: '#/components/schemas/InquiryResponse'
    InquiryResponse:
      type: object
      properties:
        id:
          type: integer
          description: 문의 ID
          format: int64
          example: 1
        title:
          type: string
          description: 문의 제목
          example: 장비 대여 관련 문의
        content:
          type: string
          description: 문의 내용
          example: 장비 대여 예약이 되지 않습니다.
        attachments:
          type: array
          items:
            type: string
            example: https://example.com/image.png, https://example.com/docs.md
            description: 첨부파일 URL
        type:
          type: string
          description: 문의 유형
          example: RENTAL
          enum:
          - RENTAL
          - RETURN
          - SYSTEM_ERROR
          - BROKEN
          - PENALTY
          - ETC
        status:
          type: string
          description: 답변 상태
          example: NOT_ANSWERED
          enum:
          - NOT_ANSWERED
          - ANSWERED
        answer:
          $ref: '#/components/schemas/InquiryAnswerResponse'
        createdAt:
          type: string
          description: 문의 작성 시간 (ISO-8601)
          example: '2025-06-02T15:34:21'
    InquiryAnswerResponse:
      type: object
      properties:
        content:
          type: string
        author:
          $ref: '#/components/schemas/AuthorResponse'
    ApiResponseInquiryListResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        data:
          $ref: '#/components/schemas/InquiryListResponse'
    InquiryListResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/InquiryResponse'
        pageable:
          $ref: '#/components/schemas/PageableInfo'
