spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/cecprod
    username: cecprod
    password: ulJLQuuOq7OxnHs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  jwt:
    secret: 'Ny0pUyf1R2xhIj8sC5e6r7t01NMinef9329HJfdo380F0h08FKf3fEF3bsy2B3n4V5c6B7n8M9l0K1J2H3G4F5D6S7a8S9D0g1F2g3H4j5L6K7l8Z9x0C1v2B3n4M5l6K7J8H92f344234f6524e65165f165wsa1f65165123231f651f651f651234616'
    access-token-validity-in-minutes: 60  # 60분
    refresh-token-validity-in-days: 14  # 14일

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      operationsSorter: method
      tagsSorter: alpha
      tryItOutEnabled: true
    api-docs:
      path: /v3/api-docs
    group-configs:
      - group: 'admin'
        paths-to-match: '/admin/**'
      - group: 'user'
        paths-to-match: '/user/**'

spring.output.ansi.enabled: always

---
spring.config.activate.on-profile: prod
spring.config.import: classpath:settings/settings-prod.yml

---
spring.config.activate.on-profile: dev
spring.config.import: classpath:settings/settings-dev.yml