services:
  nginx:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/live/api.bmvcec.store/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - ./certs/live/api.bmvcec.store/privkey.pem:/etc/nginx/certs/privkey.pem:ro
      - ./certs/certbot:/var/www/certbot
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      reverse-proxy-net:
        ipv4_address: 172.18.0.10

networks:
  reverse-proxy-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16