name: PR Build & Test Check

on:
  pull_request:
    branches: [ "main" ]
  release:
    types: [ published ]

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    services:
      docker:
        image: docker:28.1
        options: --privileged

    steps:
      - name: Check if author is allowed
        if: contains('["qkr10","geniusBrainLsm","leesunuk","GenTaram","klaus9267","Kimhasa"]', github.event.pull_request.user.login)
        run: echo "Allowed user"

      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          docker compose -f docker/db-redis/docker-compose.yml up -d

      - name: Checkout config repo
        uses: actions/checkout@v4
        with:
          repository: CEC-project/CEC-Back-Settings
          token: ${{ secrets.CEC_PAT }}
          path: src/main/resources/settings

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: SPRING_PROFILES_ACTIVE=integration-test ./gradlew test