name: PR Build Check

on:
  pull_request:
    branches: [ "main" ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4

    - name: Checkout config repo
      uses: actions/checkout@v4
      with:
        repository: CEC-project/CEC-Back-Settings
        token: ${{ secrets.CEC_PAT }}
        path: src/main/resources/settings

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build with Gradle
      run: ./gradlew build
